[package]
name = "infiniscouter-server"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
poem = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simplelog = "0.12"
tokio = { version = "1", features = ["full"] }
